name: Add QA link to issues on successful build
permissions: read-all

on:
  pull_request:
    types:
      - opened

jobs:
  check-updates:
    name: "Check package updates"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      core: ${{ steps.filter.outputs.core }}
      canary: ${{ steps.filter.outputs.canary }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 #v3.0.2
        id: filter
        with:
          filters: |
            core:
              - './packages/web-components/**'
              - './packages/react/**'
            canary:
              - './packages/canary-web-components/**'
              - './packages/canary-react/**'

  add-comment:
    needs: [check-updates]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.pull_request.head.repo.full_name == 'mi6/ic-ui-kit'
    steps:
      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch

      - uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc #v2.8.2
        if: ${{ needs.check-updates.outputs.core == 'true' }}
        with:
          message: |
            View your branch deployment here: https://mi6.github.io/ic-ui-kit/branches/${{ steps.extract_branch.outputs.branch }}/web-components
            View your React branch deployment here: https://mi6.github.io/ic-ui-kit/branches/${{ steps.extract_branch.outputs.branch }}/react
          message-id: "branch-deployment"

      - uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc #v2.8.2
        if: ${{ needs.check-updates.outputs.canary == 'true' }}
        with:
          message: |
            View your canary branch deployment here: https://mi6.github.io/ic-ui-kit/branches/${{ steps.extract_branch.outputs.branch }}/canary-web-components
            View your canary React branch deployment here: https://mi6.github.io/ic-ui-kit/branches/${{ steps.extract_branch.outputs.branch }}/canary-react
          message-id: "canary-branch-deployment"